apiVersion: v1
kind: policyset
metadata:
  id: "ps-003"
  name: "PolicySet 003"
  description: "Descripcion del policyset"
  domain: "DBB"
  owner: "equipo-x"
  version: "1.0.0"
  status: "active"
spec:
  combiningAlgorithm: "deny-overrides"
  policies:
    - id: "pol-003"
      version: "1.0.0"
