apiVersion: v1
kind: attributeprovider
metadata:
  id: "ap-003"
  name: "AttributeProvider 003"
  description: "Descripcion del provider"
  domain: "DBB"
  owner: "equipo-x"
  version: "1.0.0"
  status: "active"
spec:
  configuration:
    url: "https://example.com"
